// flow-typed signature: 1f4ec413f17a8d71b78cbdb4247529cd
// flow-typed version: <<STUB>>/dbus-native_v^0.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dbus-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dbus-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dbus-native/bin/dbus-dissect' {
  declare module.exports: any;
}

declare module 'dbus-native/bin/dbus2js' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/active-application' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/bamf' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/dbusproxy/server' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/dbusproxy/sockjs-0.3.min' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/monitor' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/monitor1' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/monitor2' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/monitor3' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/notifications' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/p2p/cli' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/p2p/serv' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/service/client' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/service/client2' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/service/server' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/service/server2' {
  declare module.exports: any;
}

declare module 'dbus-native/examples/watch-unity-menu' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/address-x11' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/bus' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/constants' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/dbuffer' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/handshake' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/hello-message' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/hexy' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/introspect' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/marshall' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/marshall1' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/message' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/parser' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/portforward' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/readline' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/server-handshake' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/server' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/signature' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/stdifaces' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/unmarshall' {
  declare module.exports: any;
}

declare module 'dbus-native/lib/validators' {
  declare module.exports: any;
}

declare module 'dbus-native/test/example-messages' {
  declare module.exports: any;
}

declare module 'dbus-native/test/js-types' {
  declare module.exports: any;
}

declare module 'dbus-native/test/signature' {
  declare module.exports: any;
}

declare module 'dbus-native/test/testdata' {
  declare module.exports: any;
}

declare module 'dbus-native/test/unmarshall-basic' {
  declare module.exports: any;
}

declare module 'dbus-native/test/unmarshall-message' {
  declare module.exports: any;
}

declare module 'dbus-native/test/utils/address' {
  declare module.exports: any;
}

declare module 'dbus-native/test/utils/packetcapture' {
  declare module.exports: any;
}

declare module 'dbus-native/test/utils/portforv' {
  declare module.exports: any;
}

declare module 'dbus-native/test/utils/tester' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dbus-native/bin/dbus-dissect.js' {
  declare module.exports: $Exports<'dbus-native/bin/dbus-dissect'>;
}
declare module 'dbus-native/bin/dbus2js.js' {
  declare module.exports: $Exports<'dbus-native/bin/dbus2js'>;
}
declare module 'dbus-native/examples/active-application.js' {
  declare module.exports: $Exports<'dbus-native/examples/active-application'>;
}
declare module 'dbus-native/examples/bamf.js' {
  declare module.exports: $Exports<'dbus-native/examples/bamf'>;
}
declare module 'dbus-native/examples/dbusproxy/server.js' {
  declare module.exports: $Exports<'dbus-native/examples/dbusproxy/server'>;
}
declare module 'dbus-native/examples/dbusproxy/sockjs-0.3.min.js' {
  declare module.exports: $Exports<'dbus-native/examples/dbusproxy/sockjs-0.3.min'>;
}
declare module 'dbus-native/examples/monitor.js' {
  declare module.exports: $Exports<'dbus-native/examples/monitor'>;
}
declare module 'dbus-native/examples/monitor1.js' {
  declare module.exports: $Exports<'dbus-native/examples/monitor1'>;
}
declare module 'dbus-native/examples/monitor2.js' {
  declare module.exports: $Exports<'dbus-native/examples/monitor2'>;
}
declare module 'dbus-native/examples/monitor3.js' {
  declare module.exports: $Exports<'dbus-native/examples/monitor3'>;
}
declare module 'dbus-native/examples/notifications.js' {
  declare module.exports: $Exports<'dbus-native/examples/notifications'>;
}
declare module 'dbus-native/examples/p2p/cli.js' {
  declare module.exports: $Exports<'dbus-native/examples/p2p/cli'>;
}
declare module 'dbus-native/examples/p2p/serv.js' {
  declare module.exports: $Exports<'dbus-native/examples/p2p/serv'>;
}
declare module 'dbus-native/examples/service/client.js' {
  declare module.exports: $Exports<'dbus-native/examples/service/client'>;
}
declare module 'dbus-native/examples/service/client2.js' {
  declare module.exports: $Exports<'dbus-native/examples/service/client2'>;
}
declare module 'dbus-native/examples/service/server.js' {
  declare module.exports: $Exports<'dbus-native/examples/service/server'>;
}
declare module 'dbus-native/examples/service/server2.js' {
  declare module.exports: $Exports<'dbus-native/examples/service/server2'>;
}
declare module 'dbus-native/examples/watch-unity-menu.js' {
  declare module.exports: $Exports<'dbus-native/examples/watch-unity-menu'>;
}
declare module 'dbus-native/index' {
  declare module.exports: $Exports<'dbus-native'>;
}
declare module 'dbus-native/index.js' {
  declare module.exports: $Exports<'dbus-native'>;
}
declare module 'dbus-native/lib/address-x11.js' {
  declare module.exports: $Exports<'dbus-native/lib/address-x11'>;
}
declare module 'dbus-native/lib/bus.js' {
  declare module.exports: $Exports<'dbus-native/lib/bus'>;
}
declare module 'dbus-native/lib/constants.js' {
  declare module.exports: $Exports<'dbus-native/lib/constants'>;
}
declare module 'dbus-native/lib/dbuffer.js' {
  declare module.exports: $Exports<'dbus-native/lib/dbuffer'>;
}
declare module 'dbus-native/lib/handshake.js' {
  declare module.exports: $Exports<'dbus-native/lib/handshake'>;
}
declare module 'dbus-native/lib/hello-message.js' {
  declare module.exports: $Exports<'dbus-native/lib/hello-message'>;
}
declare module 'dbus-native/lib/hexy.js' {
  declare module.exports: $Exports<'dbus-native/lib/hexy'>;
}
declare module 'dbus-native/lib/introspect.js' {
  declare module.exports: $Exports<'dbus-native/lib/introspect'>;
}
declare module 'dbus-native/lib/marshall.js' {
  declare module.exports: $Exports<'dbus-native/lib/marshall'>;
}
declare module 'dbus-native/lib/marshall1.js' {
  declare module.exports: $Exports<'dbus-native/lib/marshall1'>;
}
declare module 'dbus-native/lib/message.js' {
  declare module.exports: $Exports<'dbus-native/lib/message'>;
}
declare module 'dbus-native/lib/parser.js' {
  declare module.exports: $Exports<'dbus-native/lib/parser'>;
}
declare module 'dbus-native/lib/portforward.js' {
  declare module.exports: $Exports<'dbus-native/lib/portforward'>;
}
declare module 'dbus-native/lib/readline.js' {
  declare module.exports: $Exports<'dbus-native/lib/readline'>;
}
declare module 'dbus-native/lib/server-handshake.js' {
  declare module.exports: $Exports<'dbus-native/lib/server-handshake'>;
}
declare module 'dbus-native/lib/server.js' {
  declare module.exports: $Exports<'dbus-native/lib/server'>;
}
declare module 'dbus-native/lib/signature.js' {
  declare module.exports: $Exports<'dbus-native/lib/signature'>;
}
declare module 'dbus-native/lib/stdifaces.js' {
  declare module.exports: $Exports<'dbus-native/lib/stdifaces'>;
}
declare module 'dbus-native/lib/unmarshall.js' {
  declare module.exports: $Exports<'dbus-native/lib/unmarshall'>;
}
declare module 'dbus-native/lib/validators.js' {
  declare module.exports: $Exports<'dbus-native/lib/validators'>;
}
declare module 'dbus-native/test/example-messages.js' {
  declare module.exports: $Exports<'dbus-native/test/example-messages'>;
}
declare module 'dbus-native/test/js-types.js' {
  declare module.exports: $Exports<'dbus-native/test/js-types'>;
}
declare module 'dbus-native/test/signature.js' {
  declare module.exports: $Exports<'dbus-native/test/signature'>;
}
declare module 'dbus-native/test/testdata.js' {
  declare module.exports: $Exports<'dbus-native/test/testdata'>;
}
declare module 'dbus-native/test/unmarshall-basic.js' {
  declare module.exports: $Exports<'dbus-native/test/unmarshall-basic'>;
}
declare module 'dbus-native/test/unmarshall-message.js' {
  declare module.exports: $Exports<'dbus-native/test/unmarshall-message'>;
}
declare module 'dbus-native/test/utils/address.js' {
  declare module.exports: $Exports<'dbus-native/test/utils/address'>;
}
declare module 'dbus-native/test/utils/packetcapture.js' {
  declare module.exports: $Exports<'dbus-native/test/utils/packetcapture'>;
}
declare module 'dbus-native/test/utils/portforv.js' {
  declare module.exports: $Exports<'dbus-native/test/utils/portforv'>;
}
declare module 'dbus-native/test/utils/tester.js' {
  declare module.exports: $Exports<'dbus-native/test/utils/tester'>;
}
