// flow-typed signature: 482087ce295b2528897209cc4027adc4
// flow-typed version: <<STUB>>/etch_v0.8.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'etch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'etch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'etch/dist/component-helpers' {
  declare module.exports: any;
}

declare module 'etch/dist/component-widget' {
  declare module.exports: any;
}

declare module 'etch/dist/default-scheduler' {
  declare module.exports: any;
}

declare module 'etch/dist/dom' {
  declare module.exports: any;
}

declare module 'etch/dist/index' {
  declare module.exports: any;
}

declare module 'etch/dist/ref-hook' {
  declare module.exports: any;
}

declare module 'etch/dist/refs-stack' {
  declare module.exports: any;
}

declare module 'etch/dist/scheduler-assignment' {
  declare module.exports: any;
}

declare module 'etch/dist/svg-attribute-translations' {
  declare module.exports: any;
}

declare module 'etch/dist/svg-tags' {
  declare module.exports: any;
}

// Filename aliases
declare module 'etch/dist/component-helpers.js' {
  declare module.exports: $Exports<'etch/dist/component-helpers'>;
}
declare module 'etch/dist/component-widget.js' {
  declare module.exports: $Exports<'etch/dist/component-widget'>;
}
declare module 'etch/dist/default-scheduler.js' {
  declare module.exports: $Exports<'etch/dist/default-scheduler'>;
}
declare module 'etch/dist/dom.js' {
  declare module.exports: $Exports<'etch/dist/dom'>;
}
declare module 'etch/dist/index.js' {
  declare module.exports: $Exports<'etch/dist/index'>;
}
declare module 'etch/dist/ref-hook.js' {
  declare module.exports: $Exports<'etch/dist/ref-hook'>;
}
declare module 'etch/dist/refs-stack.js' {
  declare module.exports: $Exports<'etch/dist/refs-stack'>;
}
declare module 'etch/dist/scheduler-assignment.js' {
  declare module.exports: $Exports<'etch/dist/scheduler-assignment'>;
}
declare module 'etch/dist/svg-attribute-translations.js' {
  declare module.exports: $Exports<'etch/dist/svg-attribute-translations'>;
}
declare module 'etch/dist/svg-tags.js' {
  declare module.exports: $Exports<'etch/dist/svg-tags'>;
}
