// flow-typed signature: 8ba0923bc8d68c714f7b711428126a0c
// flow-typed version: <<STUB>>/wrench_v^1.5.9/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wrench'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wrench' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wrench/lib/wrench' {
  declare module.exports: any;
}

declare module 'wrench/tests/copydirsync_unix' {
  declare module.exports: any;
}

declare module 'wrench/tests/mkdir' {
  declare module.exports: any;
}

declare module 'wrench/tests/readdir' {
  declare module.exports: any;
}

declare module 'wrench/tests/readdir/foo/bar/ipsum' {
  declare module.exports: any;
}

declare module 'wrench/tests/rmdirSyncRecursive' {
  declare module.exports: any;
}

declare module 'wrench/tests/runner' {
  declare module.exports: any;
}

declare module 'wrench/tests/shown/foo/bar/ipsum' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wrench/lib/wrench.js' {
  declare module.exports: $Exports<'wrench/lib/wrench'>;
}
declare module 'wrench/tests/copydirsync_unix.js' {
  declare module.exports: $Exports<'wrench/tests/copydirsync_unix'>;
}
declare module 'wrench/tests/mkdir.js' {
  declare module.exports: $Exports<'wrench/tests/mkdir'>;
}
declare module 'wrench/tests/readdir.js' {
  declare module.exports: $Exports<'wrench/tests/readdir'>;
}
declare module 'wrench/tests/readdir/foo/bar/ipsum.js' {
  declare module.exports: $Exports<'wrench/tests/readdir/foo/bar/ipsum'>;
}
declare module 'wrench/tests/rmdirSyncRecursive.js' {
  declare module.exports: $Exports<'wrench/tests/rmdirSyncRecursive'>;
}
declare module 'wrench/tests/runner.js' {
  declare module.exports: $Exports<'wrench/tests/runner'>;
}
declare module 'wrench/tests/shown/foo/bar/ipsum.js' {
  declare module.exports: $Exports<'wrench/tests/shown/foo/bar/ipsum'>;
}
