#!/usr/bin/env bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

# Enable case-insensitive pattern matching.
shopt -s nocasematch

import_dependencies() {
  local script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
  local scripts=(install-texlive)

  source "${script_dir}/${scripts[*]}"
}

exec_ci() {
  if [[ "${APPVEYOR:-}" == true ]]; then
    local script_path="/tmp/build-package.ps1"
    curl -so ${script_path} "https://raw.githubusercontent.com/atom/ci/tj-improve-linter-selection/build-package.ps1"
    powershell -noninteractive -noprofile -command "${script_path}"
  else
    curl -s "https://raw.githubusercontent.com/atom/ci/tj-improve-linter-selection/build-package.sh" | sh
  fi
}

main() {
  import_dependencies
  install_texlive
  exec_ci
}

main "$@"
