#!/usr/bin/env bash

shopt -s extglob

cd spec/fixtures

for i in pdf pdfps pdfdvi ps dvi; do
  latexmk -$i -outdir=log-parse -jobname=file-$i file.tex
  sed -i '/^  "\//d' log-parse/file-$i.fdb_latexmk
done

rm log-parse/*.!(log|fdb_latexmk)

cd secondary-log

latexmk -pdf -jobname=biber biblatex.tex
latexmk -pdf -jobname=bibtex biblatex.tex
latexmk -pdf imakeidx.tex

sed -e 's/makeindex/zakeindex/' imakeidx.ilg >imakeidx.zlg

rm *.!(*lg|tex|bib)
rm bibtex-blx.bib
