#!/usr/bin/env bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

# Enable case-insensitive pattern matching.
shopt -s nocasematch

install_sage() {
  if [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
    echo "Installing Sage..."
    brew cask install sage
  elif [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
    echo "Installing Sage..."
    sudo apt-add-repository ppa:aims/sagemath -y
    sudo apt-get update -q
    sudo apt-get install sagemath-upstream-binary -y
  fi
}
