#!/bin/bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

_get_download_url() {
  echo "https://raw.githubusercontent.com/thomasjo/travis-texlive/master/texlive.tar.xz"
}

install_texlive() {
  echo "Downloading portable TeX Live installation..."
  if [[ "$APPVEYOR" == true ]]; then
    curl -L https://raw.githubusercontent.com/thomasjo/appveyor-texlive/master/texlive.7z | 7z e ~
  else
    curl -sL $( _get_download_url ) | tar xJC "$HOME"
  fi

  # Ensure PATH points to the platform-specific binaries.
  if [[ "$APPVEYOR" == true ]]; then
    PATH=$HOME/texlive/bin/win32:$PATH
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    PATH="$HOME/texlive/bin/x86_64-linux:$PATH"
  else
    PATH="$HOME/texlive/bin/x86_64-darwin:$PATH"
  fi
}
