#!/usr/bin/env bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

# Enable case-insensitive pattern matching.
shopt -s nocasematch

install_miktex() {
  echo "Install MiKTeX and Perl..."
  choco install miktex strawberryperl
  # Ensure PATH points to the binaries.
  echo $PATH
  export PATH="${MIKTEX_HOME}/miktex/bin/x64:${PATH}"
  mpm --admin --install=latexmk
}
