#!/usr/bin/env bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

# Ensure R is installed.
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  echo "Installing R..."
  brew update
  brew tap homebrew/science
  brew install r
fi

echo "Installing Knitr..."
Rscript -e "install.packages('knitr', '$R_LIBS_USER', 'http://cran.us.r-project.org')"
