#!/bin/bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

_get_download_url() {
  echo "https://raw.githubusercontent.com/thomasjo/travis-texlive/master/texlive.tar.xz"
}

install_texlive() {
  echo "Downloading portable TeX Live installation..."
  curl -sL $( _get_download_url ) | tar xJC "$HOME"

  # Ensure PATH points to the platform-specific binaries.
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    PATH="$HOME/texlive/bin/x86_64-linux:$PATH"
  else
    PATH="$HOME/texlive/bin/x86_64-darwin:$PATH"
  fi
}
