#!/usr/bin/env bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

ensure_r_installed() {
  if [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
    echo "Installing R..."
    brew update
    brew tap homebrew/science
    brew install r
  fi
}

install_knitr() {
  ensure_r_installed

  # Check if we need to install Knitr.
  if ! Rscript -e "library(knitr)" &> /dev/null; then
    echo "Installing Knitr..."
    [[ ! -d "${R_LIBS_USER}" ]] && mkdir -p "${R_LIBS_USER}"
    Rscript -e "install.packages('knitr', '${R_LIBS_USER}', 'http://cran.us.r-project.org')"
  else
    echo "Using cached installation of Knitr"
  fi
}
