#!/bin/bash

# Exit on failure, and treat expansion of unset variables as an error.
set -eu

_lint() {
  local npm_bin=$( npm bin )
  local paths="$1"

  "$npm_bin/standard" --verbose "$paths" | "$npm_bin/snazzy"
}

main() {
  local script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
  local source_dir=$( dirname "$script_dir" )

  local -i status=0
  echo "Linting package..." && _lint "$source_dir/lib/**/*.js" || status=$?
  echo "Linting package specs..." && _lint "$source_dir/spec/**/*.js" || status=$?
  return $status
}

main "$@"
